sindresorhus/alfy

readme.md
It looks these where the only changes I could find :).
=> tweak docs

index.js, package.json, readme.md, test/test.js
Suggestions for better names wanted!
Will add docs when we've decided on the APIs.
=> add `.matches()` and `.inputMatches()` methods

index.js, lib/cache-conf.js, package.json, readme.md, test/cache.js, test/fetch.js
Added a `fetch` method with caching and fallback mechanism.
=> add `fetch` method - fixes #6

index.js, test/fetch.js
=> fix `fetch` cache key

readme.md
add my workflow using Alfy([`alfred-hl`](https://github.com/importre/alfred-hl)) to Users
=> add alfred-hl to Users

readme.md
Added a link to my workflow for searching the elastic docs. Thx for this package!
=> add alfred-workflow-docs-elastic to Users

index.js
Fixes #11.
Don't know if you want any arguments to it or any other implementation, so consider this WIP if so :-)
=> Use `String#normalize()` in `alfy.matches()`

index.js
=> fix flaky tests - fixes #19

readme.md
Want to resolve https://github.com/SamVerschueren/alfred-link/issues/2 first and add an extra paragraph here as well referencing the moot properties in `info.plist`. So feedback about the structure, explanation, etc are more then welcome. But do not merge it yet :).
=> add alfred-link note

index.js, readme.md, test/fetch.js
Not quite sure about the documentation. Any feedback to improve that is welcome.
=> add transform function to fetch method - fixes #10

readme.md
Or do you want to show them more in the beginning of the readme?
=> add related packages

index.js, lib/update-notification.js, package.json, readme.md
Might interfer with the other PR though. If either one of these gets merged, I will rebase the other one.
=> add update notifications - fixes #24

readme.md
Improvements are always welcome.
=> Add testing section to the readme

readme.md
Hey everyone :)
This PR is adding the [alfred-vue](https://github.com/radibit/alfred-vue) workflow to the Users section in the readme.
=> Add alfred-vue workflow to Users section

readme.md
Hello, I've added my workflows to the Users section. Cheers
=> Add alfred-meteor-docs & alfred-climbing-grades-converter to Users section

readme.md
=> Add alfred-fkill to the users section

readme.md
Hey 👋🏻
The following PR adds `alfred-coolors` to the Users section.
=> Add alfred-coolors workflow to Users section

readme.md
Feel free to tell me if you have any concern with this
=> Add alfred-bitbucket to the Users section

readme.md
Hi,
Just adding a link to my workflow, let me know if there is any issue.
=> Add alfred-asana to the Users section

readme.md
Hi there. Just adding my new app as an `alfy` consumer. Thanks for maintaining this great project.
- Rui
=> Added `alfred-cacher` as an Alfred workflow to README.

readme.md
Added alfred-kaomoji and alfred-packagist workflows to the users list.
Happy hacktoberfest! :zap:
=> Add Kaomoji and Packagist workflows to Users section

readme.md
Thanks for making alfy! None of the existing VPN workflows worked for me so I was able to make my own!
=> add `alfred-vpn` to Users section

readme.md
Thank you for creating Alfy! This is an amazing library to make workflows. Clapped text is a pretty popular meme so I figured that I would create a super simple workflow for it. @sindresorhus @SamVerschueren
=> Add alfred-clap to Users section

readme.md
and update alfred-show-network-info description in Users section
=> Add alfred-currency-conversion to Users section

readme.md
Added the [alfred-reference](https://github.com/vinkla/alfred-reference#readme) package to the users list.
=> Add alfred-reference to Users section

readme.md
Hey, I created a workflow by using **alfy**, which is great! Want to add into README for more users to take this advantage.
=> Add my workflow using Alfy into README

readme.md
Alfred workflow to search for macOS packages with Homebrew.
https://github.com/vinkla/alfred-homebrew#readme
=> Add alfred-homebrew to Users section

readme.md
Add alfred-network-location-switch
=> Add alfred-network-location-switch to Users section

readme.md
Check ip using multi remote server
=> Add alfred-ip

readme.md
Thanks for making an awesome library. 💯
=> Add alfred-figma

package.json
Fixes #80, see https://github.com/SamVerschueren/alfred-link/pull/20.
=> Update alfred-link dependency

readme.md
Hey @sindresorhus, I was forced to make a new pull request because I accidentally deleted the fork before the request was approved (https://github.com/isaacs/github/issues/168). This one shouldn't have any merge conflicts. Sorry about the hassle!
=> Add alfred-trello to Users section

package.json, readme.md
- https://github.com/SamVerschueren/resolve-alfred-prefs/pull/8
- https://github.com/SamVerschueren/alfred-link/pull/24
- Resolve #110
I also updated the documentation for the latest version of Alfred.
By the way, can I apply to join the maintainers of Alfy?
=> Add suppport for Alfred 4

readme.md
Hi there ! Thanks for this great lib, it helped me create a new workflow to check the status of my builds in Travis. I wonder if you'd be open to add it to your list :-)
=> Add alfred-travis-ci to Users section 

readme.md
Elm is getting more and more popular, I think such package could be interesting to have the package documentations quickly accessible.
=> Add alfred-elm to Users section

readme.md
Thank you for a very useful tool.
I've created a workflow using alfy, and I've added it to the users section.
=> Add alfred-imagemin to Users section

readme.md
Thank you for creating an awesome library! :)
=> Add alfred-evernote-workflow to Users section

readme.md
Thank you for creating a great library :)
=> Add alfred-deno-doc to Users section

readme.md
I created this extension with alfy and just wanted to share it.
=> Add alfred-fly to Users section

readme.md
This is a workflow that fetch and show emails from multiple accounts
=> Add alfred-simple-email-fetcher to Users section

readme.md
This workflow is to search Chrome's queries, bookmarks, history, and download logs
=> Add alfred-chrome-workflow to Users section

readme.md
Thank you for a very useful tool.
I've created a workflow using alfy, and I've added it to the users section.
=> Add alfred-code to Users section

readme.md
Workflow for playing with [Amphetamine](https://apps.apple.com/app/amphetamine/id937984704).
=> Add alfred-amphetamine to Users section

readme.md
Workflow for generating various ids and copying them to your clipboard in Alfred
=> Add alfred-ids to Users section

.github/workflows/main.yml, index.js, package.json, test/fetch.js
Resolve bump with got@11.8.2
https://github.com/sindresorhus/alfy/pull/138
=> Bump got@11.8.2

readme.md
Thanks for maintaining this awesome library :)
This is a simple workflow enabling to search starred github repositories through awesome-stars repositories.
https://github.com/jopemachine/alfred-awesome-stars
=> Add alfred-awesome-stars to Users section

index.js, test/test.js
=> Normalize list items like the input value to allow matching umlauts

index.d.ts
=> Fix `mods` option TypeScript type to not require all modifiers
